apiVersion: v1
kind: Secret
metadata:
  name: django-mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD:  Q3JpczEyMytA
  MYSQL_USER:           YWRtaW4=
  MYSQL_PASSWORD:       Q3JpczEyMytA
  DJANGO_SECRET_KEY:    ZGphbmdvLWluc2VjdXJlLWU4dF94c2IrNCoqXiVqNTUtNGNecXA2c294d242a2MxcnczMyQ9Mm4kIWJedTRnejY9
