apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-microservicio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-microservicio
  template:
    metadata:
      labels:
        app: django-microservicio
    spec:

      initContainers:
      - name: wait-and-migrate
        image: dgomez9903/microservicio-django:1.0.0
        command:
          [
            "sh",
            "-c",
            "echo 'Esperando MySQL...' && \
             until nc -z ${MYSQL_HOST} ${MYSQL_PORT}; do echo 'MySQL no disponible, reintentando...'; sleep 2; done; \
             echo 'MySQL listo. Ejecutando migraciones...' && \
             python manage.py migrate --noinput"
          ]
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: MYSQL_PASSWORD

      containers:
      - name: django-app
        image: dgomez9903/microservicio-django:1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_ALLOWED_HOSTS
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_DEBUG
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: DJANGO_SECRET_KEY
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
