apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv        # nombre del PV
  labels:
    type: local
spec:
  storageClassName: manual          # usaremos un StorageClass "manual" para enlace estático
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"             # ruta en el host Minikube donde se guardarán los datos
    type: DirectoryOrCreate         # crea la carpeta si no existe
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc       # nombre del PVC
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv  # enlaza específicamente con el PV creado arriba
